CREATE TABLE author (
    author_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    description VARCHAR(400) NOT NULL,
    created_at DATE NOT NULL
);